/*
 * Phrase list retrieved from the third party website used (read the README.md file for more information)
 * this would enable the program to run without using a webserver
*/

list = [
    "be all ears",
    "barking up the wrong tree",
    "wash your hands of the matter",
    "laughter is the best medicine",
    "shoot yourself in the foot",
    "too many irons in the fire",
    "nothing certain except death and taxes",
    "judge a book by its cover",
    "throw the towel in",
    "caught with your hand in the cookie jar",
    "play second fiddle",
    "better late than never",
    "come full circle",
    "go the extra mile",
    "paint yourself into a corner",
    "stubborn as a mule",
    "your better half",
    "squeaky wheel gets the grease",
    "puppy love",
    "in the blink of an eye",
    "red letter day",
    "in over your head",
    "burst your bubble",
    "bring the house down",
    "chomping at the bit",
    "out of this world",
    "besides yourself",
    "in one ear and out the other",
    "lost his marbles",
    "come clean",
    "in the doghouse",
    "kick the bucket",
    "stuck in a rut",
    "time and tide wait for no man",
    "hold your horses",
    "sweep you off your feet",
    "on the tip of my tongue",
    "get your feathers in a bunch",
    "brown nose",
    "at your beck and call",
    "cut the rug",
    "nip it in the bud",
    "in hot water",
    "skinny as a rail",
    "rub someone the wrong way",
    "hit the road",
    "shoot the breeze",
    "fish or cut bait",
    "works like a charm",
    "get a grip",
    "let the cat out of the bag",
    "take a leaf out of his book",
    "time flies",
    "curiosity killed the cat",
    "light at the end of the tunnel",
    "patience of Job",
    "house of cards",
    "bury the hatchet",
    "play it by ear",
    "throw a fit",
    "too good to be true",
    "lay low",
    "put your foot down",
    "two peas in a pod",
    "read between the lines",
    "on the same page",
    "fence someone in",
    "hit the books",
    "water under the bridge",
    "teach an old dog new tricks",
    "eat my words",
    "everything but the kitchen sink",
    "have your cake and eat it too",
    "yuck on my yum",
    "roll out the red carpet",
    "great minds think alike",
    "blow your own horn",
    "like a fish out of water",
    "out of the frying pan and into the fire",
    "bouncing off the walls",
    "a fly on the wall",
    "at odds",
    "a bolt out of the blue",
    "not the only fish in the sea",
    "go to your head",
    "right as rain",
    "take it easy",
    "roll with the punches",
    "piece of cake",
    "on the lam",
    "easy as falling off a log",
    "make ends meet",
    "couch potato",
    "on pins and needles",
    "icing on the cake",
    "wake up and smell the roses",
    "in the lap of luxury",
    "blow it out of the water",
    "skeleton in the closet",
    "good fences make good neighbors",
    "get the ball rolling",
    "best thing since sliced bread",
    "the graveyard shift",
    "blind as a bat",
    "pass the buck",
    "burn the candle at both ends",
    "ducks in a row",
    "brownie points",
    "burn rubber",
    "recharge your batteries",
    "putting out fires",
    "eat like a bird",
    "stuck in the doldrums",
    "bite the dust",
    "stiff upper lip",
    "count chickens before they hatch",
    "every cloud has a silver lining",
    "to count on something",
    "head over heels in love",
    "like a broken record",
    "think outside the box",
    "cut above the rest",
    "keep your eye on the ball",
    "frog in your throat",
    "bright as a button",
    "measure twice cut once",
    "out like a light",
    "mind over matter",
    "back to the drawing board",
    "not my cup of tea",
    "one rotten apple spoils the whole barrel",
    "jump the gun",
    "have a blast",
    "in a heartbeat",
    "over the top",
    "whatever floats your boat",
    "what goes around comes around",
    "time to face the music",
    "that rings a bell",
    "bend over backwards",
    "down in the dumps",
    "have a cow",
    "make a beeline for",
    "good as gold",
    "ruffle a few feathers",
    "my way or the highway",
    "break a leg",
    "one smart cookie",
    "batten down the hatches",
    "go Dutch",
    "green thumb",
    "green with envy",
    "look before you leap",
    "a blessing in disguise",
    "to rough house",
    "bring home the bacon",
    "smarty pants",
    "better safe than sorry",
    "bite the hand that feeds you",
    "call it a day",
    "feeling under the weather",
    "eat like a pig",
    "hit the spot",
    "tie the knot",
    "one day at a time",
    "hit rock bottom",
    "go out on a limb",
    "get the picture",
    "needle in a haystack",
    "off the top of my head",
    "rough around the edges",
    "between a rock and a hard place",
    "set in stone",
    "your eyes are bigger than your stomach",
    "dressed to the nines",
    "in a pickle",
    "more than you can shake a stick at",
    "reinvent the wheel",
    "dodge the bullet",
    "busy bee",
    "beyond a shadow of a doubt",
    "hit the ground running",
    "get the show on the road",
    "too many cooks in the kitchen",
    "go against the grain",
    "fat chance",
    "beat swords into ploughshares",
    "fly off the handle",
    "money burns a hole in your pocket",
    "grass is always greener on the other side",
    "the whole kit and caboodle",
    "burning bridges",
    "shape up or ship out",
    "off the hook",
    "just a drop in the bucket",
    "you catch more flies with honey than with vinegar",
    "over the moon",
    "in your dreams",
    "out of my hair",
    "how do you like them apples",
    "take my hat off to you",
    "bigger fish to fry",
    "heart of gold",
    "jack up the price",
    "cast pearls before swine",
    "ants in your pants",
    "pull the wool over your eyes",
    "put your foot in your mouth",
    "once in a blue moon",
    "full of hot air",
    "spitting image",
    "depths of despair",
    "rise above the blues",
    "fraidycat",
    "egg on your face",
    "get your goat",
    "behind the times",
    "steal my thunder",
    "keep your chin up",
    "other side of the coin",
    "bad egg",
    "make a mountain out of a molehill",
    "memory like an elephant",
    "crocodile tears",
    "chew the fat",
    "all skin and bone",
    "rain on your parade",
    "sweet tooth",
    "early bird gets the worm",
    "turn a new leaf",
    "push the envelope",
    "easier said than done",
    "carry a tune",
    "cost an arm and a leg",
    "when in Rome",
    "take it with a grain of salt",
    "out of my league",
    "look out for number one",
    "know it like the back of your hand",
    "someone with a hollow leg",
    "bite off more than you can chew",
    "eat like a horse",
    "birds of a feather flock together",
    "lesser of two evils",
    "everybody and their dog",
    "back to square one",
    "all your eggs in one basket",
    "sticks and stones",
    "a friend in need is a friend indeed",
    "stick out like a sore thumb",
    "the new black",
    "like shooting fish in a barrel",
    "quit cold turkey",
    "glued to your seat",
    "creme de la creme",
    "rub salt in an open wound",
    "every dog has its day",
    "silence is golden",
    "dog and pony show",
    "horse of a different color",
    "put it on the back burner",
    "burning daylight",
    "at the bottom of the totem pole",
    "on cloud nine",
    "when push comes to shove",
    "as the crow flies",
    "winner takes all",
    "put two and two together",
    "give him a run for his money",
    "one foot in the door",
    "beauty is only skin deep",
    "pop the question",
    "knock your socks off",
    "make good time",
    "salt of the earth",
    "grin and bear it",
    "up a creek without a paddle",
    "in a nutshell",
    "small potatoes",
    "in a jam",
    "over the hill",
    "read my lips",
    "hit the sack",
    "the black sheep",
    "ballpark figure",
    "short end of the stick",
    "take one for the team",
    "a fifth wheel",
    "the whole nine yards",
    "grab the bull by the horns",
    "chip on your shoulder",
    "wet blanket",
    "so hungry I could eat a horse",
    "a happy camper",
    "look a gift horse in the mouth",
    "like taking candy from a baby",
    "cry over spilt milk",
    "all bark and no bite",
    "down to the nitty gritty",
    "put the cart before the horse",
    "draw the shortest straw",
    "take a hike",
    "hold your tongue",
    "keep your fingers crossed",
    "basket case",
    "one bad apple",
    "let bygones be bygones",
    "at the top of your lungs",
    "like watching paint dry",
    "put the pedal to the metal",
    "cat got your tongue",
    "from the bottom of my heart",
    "clear as mud",
    "down to the wire",
    "wild goose chase",
    "when pigs fly",
    "a little bird told me",
    "apple of my eye",
    "have two left feet",
    "in the zone",
    "go to town",
    "a penny saved is a penny earned",
    "like pulling teeth",
    "the calm before the storm",
    "peanut gallery",
    "hold down the fort",
    "heard it through the grapevine",
    "a long shot",
    "give him a piece of my mind",
    "like a kid in a candy store",
    "throw a wrench in the works",
    "spill the beans",
    "beat around the bush",
    "the way the cookie crumbles",
    "ball is in your court",
    "hit the nail on the head",
    "put hair on your chest",
    "chip off the old block",
    "cross the bridge when we come to it",
    "the cold shoulder",
    "get cold feet",
    "join the club",
    "this too shall pass",
    "in the nick of time",
    "dropping like flies",
    "in the same boat",
    "wake up on the wrong side of the bed",
    "scared stiff",
    "better the devil you know",
    "open a can of worms",
    "if wishes were horses",
    "comparing apples and oranges",
    "bats in the belfry",
    "on top of the world",
    "fit as a fiddle",
    "wallflower",
    "get your feet wet",
    "pick up the pace",
    "butterflies in your stomach",
    "give my two cents",
    "feeling blue",
    "on the edge of your seat",
    "avoid like the plague",
    "at the end of your rope",
    "big fish in a small pond",
    "knock on wood",
    "raining cats and dogs",
    "turn the tables",
    "loose cannon",
    "blood is thicker than water",
    "clean slate",
    "out and about",
    "like a deer in the headlights",
    "bull in a china closet"
  ]